#!/bin/bash
#SBATCH --job-name=create_input
#SBATCH --output=prep-logs/slurm-%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=1             # 1 parallel task
#SBATCH --time=0:30:00
#SBATCH --qos=stellar-debug    # Stellar debug queue (max 30 min)
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=mpatel26@thea.energy

# 1. Threading and Parallelism Flags
# This tricks JAX into seeing 64 independent devices on the CPU
export XLA_FLAGS="--xla_force_host_platform_device_count=64 --xla_cpu_multi_thread_eigen=true"

export OMP_NUM_THREADS=96
export MKL_NUM_THREADS=96
export NUMBA_NUM_THREADS=96
# 2. JAX Precision and Backend behavior
export JAX_ENABLE_X64=True
export JAX_PLATFORMS=cpu
export XLA_PYTHON_CLIENT_PREALLOCATE=false

# 3. Environment Setup
module purge
module load anaconda3/2024.6

source $(conda info --base)/etc/profile.d/conda.sh
conda activate ascot-develop-mp


PARAMS="alphaprep-params.json"

#srun -n 1 -c 64 --cpu-bind=cores python -u create-input.py --params=$PARAMS
srun -n 1 -c 64 --cpu-bind=cores python -u create-input-NoStellSym.py --params=$PARAMS

srun -n 1 -c 64 --cpu-bind=cores python -u set_field.py --params=$PARAMS