#!/bin/bash
#SBATCH --job-name=create_inputs
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --time=0:30:00
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH --account=m4477
#SBATCH --mail-type=begin,end,fail
#SBATCH --mail-user=mpatel26@thea.energy

# 1. Threading and Parallelism Flags
# This tricks JAX into seeing 64 independent devices on the CPU
export XLA_FLAGS="--xla_force_host_platform_device_count=64 --xla_cpu_multi_thread_eigen=true"

export OMP_NUM_THREADS=64
export MKL_NUM_THREADS=64
export NUMBA_NUM_THREADS=64
# 2. JAX Precision and Backend behavior
export JAX_ENABLE_X64=True
export JAX_PLATFORMS=cpu
export XLA_PYTHON_CLIENT_PREALLOCATE=false

# 3. Environment Setup
module purge
module load python


source $(conda info --base)/etc/profile.d/conda.sh
conda activate ascot-develop-mp

INP_DIR="/pscratch/sd/m/mpatel26/equil/"
OUT_DIR="/pscratch/sd/m/mpatel26/ascot_h5s/convergence_studies/"

EQUIL_NAME="equil_Helios_G1600-12-89_QA2e-1_Bxdl25_free_L12_M12_N20.h5"
ENCIRCLING_NAME="encircling_G1600-12-89_QA2e-1_Bxdl25.h5"
SHAPING_NAME="shaping_G1600-12-89_QA2e-1_Bxdl25.h5"
WALL_NAME="divertor_with_targets.vtk"
#WALL_NAME="conformal10cm-newscheme.vtk"

SIM_NAME="restarting_from_biotsavart_lcfs-usingFO"
NMRK=10000
SIMMODE='prt'
CELL_AREA=0.01
USE_MIXED_FIELD=False
FPP=958.0
SOL_PROFILE="decay"
WALL_OFFSET=100
COLLECT_DIST=False

# Engineering Wall Input
srun -n 1 -c 64 --cpu-bind=cores python -u create-input.py  --wall_name=$WALL_NAME --sim_name=$SIM_NAME --simmode=$SIMMODE --wall_offset=$WALL_OFFSET --cell_area=$CELL_AREA --inp_dir=$INP_DIR --out_dir=$OUT_DIR --nmrk=$NMRK --equil_name=$EQUIL_NAME --encircling_name=$ENCIRCLING_NAME --shaping_name=$SHAPING_NAME --rescale_FPP=$FPP --use_mixed_field=$USE_MIXED_FIELD --sol_profile=$SOL_PROFILE --collect_dist=$COLLECT_DIST

#Conformal Offset Wall Input
#srun -n 1 -c 64 --cpu-bind=cores python -u create-input.py --sim_name=$SIM_NAME --simmode=$SIMMODE --wall_offset=$WALL_OFFSET --cell_area=$CELL_AREA --inp_dir=$INP_DIR --out_dir=$OUT_DIR --nmrk=$NMRK --equil_name=$EQUIL_NAME --encircling_name=$ENCIRCLING_NAME --shaping_name=$SHAPING_NAME --rescale_FPP=$FPP --use_mixed_field=$USE_MIXED_FIELD --sol_profile=$SOL_PROFILE --collect_dist=$COLLECT_DIST

#LCFS Wall Input
#srun -n 1 -c 64 --cpu-bind=cores python -u create-input.py --sim_name=$SIM_NAME --simmode=$SIMMODE --wall_offset=$WALL_OFFSET --cell_area=$CELL_AREA --inp_dir=$INP_DIR --out_dir=$OUT_DIR --nmrk=$NMRK --equil_name="equil_G1600_DESC_fixed.h5" --rescale_FPP=$FPP --use_mixed_field=$USE_MIXED_FIELD --sol_profile=$SOL_PROFILE --collect_dist=$COLLECT_DIST

#Set sim mode to GC+FO
#srun -n 1 -c 64 --cpu-bind=cores python -u set_hybrid.py --sim_name=$SIM_NAME 